version: '3'
services:
  stockmarketapp:
    build: 
        context: ./front-end
    ports:
        - "8080:8080"
    environment:
        MIDDLEWARE_EP: http://middleware:9000
        PORT: 8080
    depends_on:
        - middleware
  middleware:
    build: 
        context: ./middleware
    ports:
      - "9000:9000"
    environment:
        TODAY_SERVICE_EP: http://today-service:6000
        BITCOIN_SERVICE_EP: http://bitcoin-service:5000
        PORT: 9000
    depends_on:
        - today-service
        - bitcoin-service
  today-service:
    build: 
        context: ./back-end
    ports:
        - "6000:6000"
    environment:
        TYPE: today
        PORT: 6000
  bitcoin-service:
    build: 
        context: ./back-end
    ports:
        - "5000:5000"
    environment:
        TYPE: bitcoin
        PORT: 5000
    