apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end-deployment
  labels:
    app: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      containers:
      - name: front-end
        image: front-end
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: MIDDLEWARE_EP
          value: "http://middleware-service"
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
    name: front-end-service
spec:
    selector:
        app: front-end
    type: NodePort
    ports:
      - protocol: TCP
        port: 80
        targetPort: 8080